version: '3.8'

services:
  source:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    container_name: mysql-source
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "13306:3306"
    volumes:
      - db-source:/var/lib/mysql
      - db-source:/var/lib/mysql-files
      - ./docker/source.cnf:/etc/mysql/my.cnf
    networks:
      - mysql_network

  replica:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    container_name: mysql-replica
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "13307:3306"
    volumes:
      - db-replica:/var/lib/mysql
      - db-replica:/var/lib/mysql-files
      - ./docker/replica.cnf:/etc/mysql/my.cnf
    networks:
      - mysql_network

volumes:
  db-source:
  db-replica:

networks:
  mysql_network:
    driver: bridge
